/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ScoreEntry = IDL.Record({
  'email' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const QuizScore = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const UserStats = IDL.Record({
  'quizScores' : IDL.Vec(QuizScore),
  'countriesViewed' : IDL.Vec(IDL.Text),
  'playersSearched' : IDL.Vec(IDL.Text),
});
export const Category = IDL.Text;
export const Country = IDL.Text;
export const PlayerQuery = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScores' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'getUserStats' : IDL.Func([IDL.Text], [IDL.Opt(UserStats)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'submitQuizScore' : IDL.Func([IDL.Text, IDL.Nat, Category, IDL.Nat], [], []),
  'trackCountryView' : IDL.Func([IDL.Text, Country], [], []),
  'trackPlayerSearch' : IDL.Func([IDL.Text, PlayerQuery], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ScoreEntry = IDL.Record({
    'email' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const QuizScore = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const UserStats = IDL.Record({
    'quizScores' : IDL.Vec(QuizScore),
    'countriesViewed' : IDL.Vec(IDL.Text),
    'playersSearched' : IDL.Vec(IDL.Text),
  });
  const Category = IDL.Text;
  const Country = IDL.Text;
  const PlayerQuery = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScores' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
    'getUserStats' : IDL.Func([IDL.Text], [IDL.Opt(UserStats)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'submitQuizScore' : IDL.Func(
        [IDL.Text, IDL.Nat, Category, IDL.Nat],
        [],
        [],
      ),
    'trackCountryView' : IDL.Func([IDL.Text, Country], [], []),
    'trackPlayerSearch' : IDL.Func([IDL.Text, PlayerQuery], [], []),
  });
};

export const init = ({ IDL }) => { return []; };