/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export type Country = string;
export type PlayerQuery = string;
export interface QuizScore {
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
  'category' : string,
}
export interface ScoreEntry {
  'email' : string,
  'score' : bigint,
  'timestamp' : bigint,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'quizScores' : Array<QuizScore>,
  'countriesViewed' : Array<string>,
  'playersSearched' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<ScoreEntry>>,
  'getTopScores' : ActorMethod<[], Array<ScoreEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserScores' : ActorMethod<[string], Array<ScoreEntry>>,
  'getUserStats' : ActorMethod<[string], [] | [UserStats]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveScore' : ActorMethod<[string, bigint, string], undefined>,
  'submitQuizScore' : ActorMethod<
    [string, bigint, Category, bigint],
    undefined
  >,
  'trackCountryView' : ActorMethod<[string, Country], undefined>,
  'trackPlayerSearch' : ActorMethod<[string, PlayerQuery], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];